### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by buzzzo** [dot-mike/nmscustomfields#3]
When trying to install the module i've receive the following error:

Type of DotMike\NmsCustomFields\Hooks\MenuHook::$view must be string (as in class App\Plugins\Hooks\MenuEntryHook) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Type of DotMike\\NmsCustomFields\\Hooks\\MenuHook::$view must be string (as in class App\\Plugins\\Hooks\\MenuEntryHook) at /opt/librenms/vendor/dot-mike/nmscustomfields/src/Hooks/MenuHook.php:7)"}

An more in general in logs.

The error prevents the correct render of the librenms web ui (in other words it crashes librenms)

**Comment by dot-mike** [comment]
What is your LibreNMS Version?

**Comment by buzzzo** [comment]
24.7.0-41-gb62a4bacd - Wed Aug 07 2024 04:19:50 GMT+0200



[24.7.0-41-gb62a4bacd - Wed Aug 07 2024 04:19:50 GMT+0200](https://www.librenms.org/changelog.html)

**Comment by buzzzo** [comment]
So nothing?

**Comment by notyettested** [comment]
i ran into the same issue. i then just corrected what the error messages stated (/opt/librenms/vendor/dot-mike/nmscustomfileds/src/Hooks/... change the "public view ..." parts to "public string view ...") and now it installs correctly but no Plugin shows up in the librenms WebUI.

**Comment by dot-mike** [comment]
Sorry for the prolonged delay. I've taken care of this issue, thanks for reporting it!Sorry for the prolonged delay. I've taken care of this issue, thanks for reporting it!
